BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "EntityValues" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"createDate"	TEXT NOT NULL,
	"entityId"	INTEGER NOT NULL,
	"key"	TEXT,
	"value"	TEXT
);
CREATE TABLE IF NOT EXISTS "EntityRelations" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"createDate"	TEXT NOT NULL,
	"entityId1"	INTEGER NOT NULL,
	"entityId2"	INTEGER NOT NULL,
	"type"	TEXT,
	"value"	TEXT
);
CREATE TABLE IF NOT EXISTS "Entities" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"createDate"	TEXT NOT NULL,
	"name"	TEXT,
	"content"	TEXT,
	"type"	TEXT
);
COMMIT;
